### ISSUE TITLE
Language Snippets

### ISSUE THREAD

**Issue by endersoncosta** [herbsjs/buchu#12]
Using the HerbsJS i could see that intellisense fails to show the code complement, then I did an extension for the vscode with some snippets, follow the links.

[Github Repository](https://github.com/endersoncosta/herbs-snippets)
[Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=EndersonCosta.herbs-snippets)

note: This version just includes **Buchu** and **Gotu**.

**Comment by jhomarolo** [comment]
Hello @endersoncosta , I think the contribution is really valid, even to bring the feeling of a "complete" library.

But I think there is a need to considerably improve the documentation because I know the library, I didn't fully understand it.

Some docs you can rely on: https://marketplace.visualstudio.com/items?itemName=jmsv.JavaScriptSnippetsStandard

This model of having a "gif" image showing the use I think is almost essential to show in practice how it works: https://github.com/abusaidm/html-snippets

After that I think we will have a relatively good version to release.

**Comment by endersoncosta** [comment]
I fixed some snippets in the extension, then I took advantage to improve the documentation with your tips.

**Comment by jhomarolo** [comment]
Huge doc improvement!

I Believe that the documentation has become much more didactic in this way.
What is your suggestion in this case? Do you intend to incorporate in our repository or keep in yours?

@dalssoft what did you think about this?

**Comment by dalssoft** [comment]
Loved it! impressive contribution 
Thanks a lot @endersoncosta !

Would you be willing to donate this repo to the official Herbs org and maintain it?

**Comment by endersoncosta** [comment]
Yes! This project is just a child of HerbsJS. So naturally I would like to integrate into the official repository.

**Comment by dalssoft** [comment]
Great! Whenever you want

**Comment by endersoncosta** [comment]
We'll move the snippets to an official **HerbsJS** repository?
